// <auto-generated />
namespace MyWareHouse.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Product_NameMax1204 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_NameMax1204));
        
        string IMigrationMetadata.Id
        {
            get { return "201710131334048_Product_NameMax1204"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
